spring.application.name=agendamento

# Configurações do H2 Database (Baseado em Arquivo)
spring.datasource.url=jdbc:h2:file:./data/agendamento_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console H2 para visualizar o BD no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Spring Data JPA (Hibernate)
# MUDANÇA AQUI: 'create' forçará a recriação do esquema (incluindo sequências) a cada início.
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect